# Generated by Django 5.2.4 on 2025-09-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='lop_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='salary_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unpaid salary from previous months', max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='total_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
