# Generated by Django 5.0.6 on 2026-01-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsslConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.CharField(default='192.168.1.201', max_length=100)),
                ('device_port', models.IntegerField(default=4370)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
