# Generated by Django 5.0.6 on 2026-04-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_created_at_attendance_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='approved',
        ),
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
