# Generated by Django 5.2.4 on 2025-07-03 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('salary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeallowance',
            name='allowance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.allowance'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.category'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.designation'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeeprofile'),
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeeprofile'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeetype'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeallowance',
            unique_together={('employee', 'allowance')},
        ),
    ]
