# Generated by Django 5.2.4 on 2025-07-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='first_name',
            field=models.CharField(default='PlaceholderFirst', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='username',
            field=models.CharField(default='PlaceholderLast', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='salary_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
