# Generated by Django 5.2.4 on 2025-09-26 11:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employeeprofile_salary_per_day_and_more'),
        ('salary', '0003_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeededuction',
            name='name',
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='deduction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.deduction'),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='method',
            field=models.CharField(choices=[('next_month', 'Next Month Salary'), ('installments', 'Equal Deduction for X Months'), ('annual_leave', 'Deduction from Annual Leave Salary')], default='next_month', max_length=20),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeededuction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
