# Generated by Django 5.2.4 on 2025-09-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_employeeprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeededuction',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='reimbursed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='remaining_installments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
